// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://swagger.json` | (string & {});
};

export type AddStockRequest = {
    quantityToAdd?: number;
    note?: string | null;
};

export type AssignUserToStoreCommand = {
    storeId?: string;
    userId?: string;
    role?: UserRole;
};

export type BrandDto = {
    id?: string;
    nameEn?: string | null;
    nameAr?: string | null;
    descriptionEn?: string | null;
    descriptionAr?: string | null;
    logoUrl?: string | null;
    website?: string | null;
    country?: string | null;
    active?: boolean;
    productCount?: number;
    createdAt?: string;
};

export type BrandReportDto = {
    brandNameEn?: string | null;
    brandNameAr?: string | null;
    brandLogoUrl?: string | null;
    revenue?: number;
    unitsSold?: number;
};

export type CategoryDto = {
    id?: string;
    nameEn?: string | null;
    nameAr?: string | null;
    descriptionEn?: string | null;
    descriptionAr?: string | null;
    imageUrl?: string | null;
    iconName?: string | null;
    color?: string | null;
    parentId?: string | null;
    parentNameEn?: string | null;
    parentNameAr?: string | null;
    sortOrder?: number;
    active?: boolean;
    productCount?: number;
    createdAt?: string;
    children?: Array<CategoryDto> | null;
};

export type CategoryReportDto = {
    categoryNameEn?: string | null;
    categoryNameAr?: string | null;
    categoryColor?: string | null;
    revenue?: number;
    unitsSold?: number;
};

export type ChangePasswordCommand = {
    userId?: string;
    currentPassword?: string | null;
    newPassword?: string | null;
};

export type CreateCustomerCommand = {
    request?: CreateCustomerRequest;
};

export type CreateCustomerRequest = {
    nameEn?: string | null;
    nameAr?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    taxNumber?: string | null;
};

export type CreateExpenseCategoryCommand = {
    nameEn?: string | null;
    nameAr?: string | null;
};

export type CreateExpenseRequest = {
    title?: string | null;
    expenseDate?: string;
    categoryId?: string;
    amount?: number;
    paymentMethod?: string | null;
    receiptUrl?: string | null;
    notes?: string | null;
};

export type CreateInvoiceItemRequest = {
    productId?: string;
    description?: string | null;
    descriptionAr?: string | null;
    quantity?: number;
    unitPrice?: number;
    discount?: number;
};

export type CreateOrderItemRequest = {
    productId?: string;
    quantity?: number;
};

export type CreateOrderRequest = {
    items?: Array<CreateOrderItemRequest> | null;
    paymentMethod?: string | null;
    amountPaid?: number;
    notes?: string | null;
};

export type CreatePaymentInvoiceRequest = {
    invoiceDate?: string;
    dueDate?: string;
    customerId?: string;
    taxRate?: number;
    discountAmount?: number;
    paymentMethod?: string | null;
    notes?: string | null;
    items?: Array<CreateInvoiceItemRequest> | null;
};

export type CreatePurchaseInvoiceRequest = {
    supplierInvoiceNumber?: string | null;
    invoiceDate?: string;
    dueDate?: string;
    supplierId?: string;
    taxRate?: number;
    shippingCost?: number;
    paymentMethod?: string | null;
    notes?: string | null;
    updateStockOnApproval?: boolean;
    items?: Array<CreatePurchaseItemRequest> | null;
};

export type CreatePurchaseItemRequest = {
    productId?: string;
    description?: string | null;
    descriptionAr?: string | null;
    quantity?: number;
    unitCost?: number;
};

export type CreateStoreCommand = {
    request?: CreateStoreRequest;
};

export type CreateStoreRequest = {
    name?: string | null;
    nameAr?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    taxNumber?: string | null;
    logoUrl?: string | null;
    currency?: string | null;
};

export type CreateSupplierCommand = {
    request?: CreateSupplierRequest;
};

export type CreateSupplierRequest = {
    nameEn?: string | null;
    nameAr?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    taxNumber?: string | null;
    contactPerson?: string | null;
    website?: string | null;
};

export type CreateTaxCommand = {
    request?: CreateTaxRequest;
};

export type CreateTaxRequest = {
    nameEn?: string | null;
    nameAr?: string | null;
    type?: string | null;
    value?: number;
    active?: boolean;
    isDefault?: boolean;
};

export type CreateUnitCommand = {
    request?: CreateUnitRequest;
};

export type CreateUnitConversionCommand = {
    request?: CreateUnitConversionRequest;
};

export type CreateUnitConversionRequest = {
    fromUnitId?: string;
    toUnitId?: string;
    factor?: number;
    active?: boolean;
};

export type CreateUnitRequest = {
    nameEn?: string | null;
    nameAr?: string | null;
    symbol?: string | null;
    type?: string | null;
    active?: boolean;
};

export type CreateUserCommand = {
    name?: string | null;
    email?: string | null;
    password?: string | null;
    role?: string | null;
};

export type CustomerDto = {
    id?: string;
    nameEn?: string | null;
    nameAr?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    taxNumber?: string | null;
    totalInvoiced?: number;
    totalPaid?: number;
    balance?: number;
    createdAt?: string;
};

export type DailyReportRowDto = {
    date?: string;
    orders?: number;
    revenue?: number;
    avgOrderValue?: number;
    profit?: number;
};

export type DashboardStatsDto = {
    revenueToday?: number;
    revenueTrend?: number;
    ordersToday?: number;
    ordersTrend?: number;
    avgOrderValue?: number;
    avgOrderTrend?: number;
    lowStockCount?: number;
};

export type ExpenseCategoryDto = {
    id?: string;
    nameEn?: string | null;
    nameAr?: string | null;
    active?: boolean;
};

export type ExpenseDto = {
    id?: string;
    title?: string | null;
    expenseDate?: string;
    categoryId?: string;
    categoryNameEn?: string | null;
    categoryNameAr?: string | null;
    amount?: number;
    paymentMethod?: string | null;
    receiptUrl?: string | null;
    notes?: string | null;
    recordedByName?: string | null;
    createdAt?: string;
};

export type HourlySaleDto = {
    hour?: number;
    revenue?: number;
    orderCount?: number;
};

export type ImageOrder = {
    imageId?: string;
    sortOrder?: number;
};

export type InventoryItemDto = {
    id?: string;
    productId?: string;
    productNameEn?: string | null;
    productNameAr?: string | null;
    productImageUrl?: string | null;
    categoryNameEn?: string | null;
    categoryNameAr?: string | null;
    currentStock?: number;
    reorderLevel?: number;
    status?: string | null;
    lastUpdated?: string;
};

export type LoginCommand = {
    email?: string | null;
    password?: string | null;
};

export type LoginResponse = {
    token?: string | null;
    refreshToken?: string | null;
    expiresAt?: string;
    user?: UserDto;
};

export type MarkInvoicePaidRequestModel = {
    amountPaid?: number | null;
};

export type OrderDto = {
    id?: string;
    orderNumber?: string | null;
    cashierId?: string;
    cashierName?: string | null;
    subtotal?: number;
    taxRate?: number;
    taxAmount?: number;
    discountAmount?: number;
    total?: number;
    amountPaid?: number;
    change?: number;
    paymentMethod?: string | null;
    status?: string | null;
    notes?: string | null;
    createdAt?: string;
    items?: Array<OrderItemDto> | null;
};

export type OrderItemDto = {
    id?: string;
    productId?: string;
    productName?: string | null;
    productNameAr?: string | null;
    unitPrice?: number;
    quantity?: number;
    lineTotal?: number;
};

export type PaymentInvoiceDto = {
    id?: string;
    invoiceNumber?: string | null;
    invoiceDate?: string;
    dueDate?: string;
    customerId?: string;
    customerNameEn?: string | null;
    customerNameAr?: string | null;
    customerEmail?: string | null;
    subtotal?: number;
    taxRate?: number;
    taxAmount?: number;
    discountAmount?: number;
    total?: number;
    amountPaid?: number;
    balance?: number;
    status?: string | null;
    paymentMethod?: string | null;
    notes?: string | null;
    paidAt?: string | null;
    sentAt?: string | null;
    createdAt?: string;
    items?: Array<PaymentInvoiceItemDto> | null;
};

export type PaymentInvoiceItemDto = {
    id?: string;
    productId?: string;
    description?: string | null;
    descriptionAr?: string | null;
    quantity?: number;
    unitPrice?: number;
    discount?: number;
    lineTotal?: number;
};

export type ProductDto = {
    id?: string;
    nameEn?: string | null;
    nameAr?: string | null;
    descriptionEn?: string | null;
    descriptionAr?: string | null;
    sku?: string | null;
    barcode?: string | null;
    categoryId?: string;
    categoryNameEn?: string | null;
    categoryNameAr?: string | null;
    categoryColor?: string | null;
    brandId?: string | null;
    brandNameEn?: string | null;
    brandNameAr?: string | null;
    brandLogoUrl?: string | null;
    costPrice?: number;
    sellPrice?: number;
    stockQty?: number;
    reorderLevel?: number;
    baseUnitId?: string;
    baseUnitNameEn?: string | null;
    baseUnitNameAr?: string | null;
    baseUnitSymbol?: string | null;
    purchaseUnitId?: string | null;
    purchaseUnitNameEn?: string | null;
    purchaseUnitNameAr?: string | null;
    purchaseUnitSymbol?: string | null;
    conversionFactor?: number;
    taxId?: string;
    taxNameEn?: string | null;
    taxNameAr?: string | null;
    taxRate?: number;
    taxType?: string | null;
    active?: boolean;
    imageUrls?: Array<string> | null;
    createdAt?: string;
    updatedAt?: string | null;
};

export type ProductDtoPaginatedList = {
    data?: Array<ProductDto> | null;
    page?: number;
    limit?: number;
    total?: number;
    readonly totalPages?: number;
};

export type PurchaseInvoiceDto = {
    id?: string;
    referenceNumber?: string | null;
    supplierInvoiceNumber?: string | null;
    invoiceDate?: string;
    dueDate?: string;
    supplierId?: string;
    supplierNameEn?: string | null;
    supplierNameAr?: string | null;
    subtotal?: number;
    taxRate?: number;
    taxAmount?: number;
    shippingCost?: number;
    total?: number;
    amountPaid?: number;
    balance?: number;
    status?: string | null;
    paymentMethod?: string | null;
    stockUpdated?: boolean;
    notes?: string | null;
    approvedByName?: string | null;
    approvedAt?: string | null;
    createdAt?: string;
    items?: Array<PurchaseInvoiceItemDto> | null;
};

export type PurchaseInvoiceItemDto = {
    id?: string;
    productId?: string;
    productNameEn?: string | null;
    productNameAr?: string | null;
    description?: string | null;
    descriptionAr?: string | null;
    quantity?: number;
    unitCost?: number;
    lineTotal?: number;
};

export type ReceiptDto = {
    id?: string;
    receiptNumber?: string | null;
    orderId?: string;
    subtotal?: number;
    taxAmount?: number;
    discountAmount?: number;
    total?: number;
    amountPaid?: number;
    change?: number;
    paymentMethod?: string | null;
    createdAt?: string;
};

export type RecentOrderDto = {
    id?: string;
    orderNumber?: string | null;
    type?: string | null;
    total?: number;
    status?: string | null;
    createdAt?: string;
};

export type RefreshTokenCommand = {
    refreshToken?: string | null;
};

export type ReportSummaryDto = {
    totalRevenue?: number;
    totalOrders?: number;
    topProductNameEn?: string | null;
    topProductNameAr?: string | null;
    profitMargin?: number;
};

export type StockLevelDto = {
    productId?: string;
    productNameEn?: string | null;
    productNameAr?: string | null;
    currentStock?: number;
    maxStock?: number;
    status?: string | null;
};

export type StoreDto = {
    id?: string;
    name?: string | null;
    nameAr?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    taxNumber?: string | null;
    logoUrl?: string | null;
    currency?: string | null;
    active?: boolean;
    createdAt?: string;
};

export type SupplierDto = {
    id?: string;
    nameEn?: string | null;
    nameAr?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    taxNumber?: string | null;
    contactPerson?: string | null;
    website?: string | null;
    totalPurchases?: number;
    createdAt?: string;
};

export type TaxDto = {
    id?: string;
    nameEn?: string | null;
    nameAr?: string | null;
    type?: string | null;
    value?: number;
    active?: boolean;
    isDefault?: boolean;
    createdAt?: string;
};

export type TopProductDto = {
    productId?: string;
    productNameEn?: string | null;
    productNameAr?: string | null;
    productImageUrl?: string | null;
    unitsSold?: number;
    revenue?: number;
};

export type UnitConversionDto = {
    id?: string;
    fromUnitId?: string;
    fromUnitSymbol?: string | null;
    toUnitId?: string;
    toUnitSymbol?: string | null;
    factor?: number;
    active?: boolean;
    createdAt?: string;
};

export type UnitDto = {
    id?: string;
    nameEn?: string | null;
    nameAr?: string | null;
    symbol?: string | null;
    type?: string | null;
    active?: boolean;
    createdAt?: string;
};

export type UpdateCustomerCommand = {
    id?: string;
    request?: UpdateCustomerRequest;
};

export type UpdateCustomerRequest = {
    nameEn?: string | null;
    nameAr?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    taxNumber?: string | null;
};

export type UpdateExpenseCategoryCommand = {
    id?: string;
    nameEn?: string | null;
    nameAr?: string | null;
    active?: boolean;
};

export type UpdateExpenseCommand = {
    id?: string;
    request?: UpdateExpenseRequest;
};

export type UpdateExpenseRequest = {
    title?: string | null;
    expenseDate?: string | null;
    categoryId?: string | null;
    amount?: number | null;
    paymentMethod?: string | null;
    receiptUrl?: string | null;
    notes?: string | null;
};

export type UpdateStoreCommand = {
    request?: UpdateStoreRequest;
};

export type UpdateStoreRequest = {
    id?: string;
    name?: string | null;
    nameAr?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    taxNumber?: string | null;
    logoUrl?: string | null;
    currency?: string | null;
    active?: boolean;
};

export type UpdateSupplierCommand = {
    id?: string;
    request?: UpdateSupplierRequest;
};

export type UpdateSupplierRequest = {
    nameEn?: string | null;
    nameAr?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    taxNumber?: string | null;
    contactPerson?: string | null;
    website?: string | null;
};

export type UpdateTaxCommand = {
    id?: string;
    request?: UpdateTaxRequest;
};

export type UpdateTaxRequest = {
    nameEn?: string | null;
    nameAr?: string | null;
    type?: string | null;
    value?: number | null;
    active?: boolean | null;
    isDefault?: boolean | null;
};

export type UpdateUnitCommand = {
    id?: string;
    request?: UpdateUnitRequest;
};

export type UpdateUnitRequest = {
    nameEn?: string | null;
    nameAr?: string | null;
    symbol?: string | null;
    type?: string | null;
    active?: boolean | null;
};

export type UpdateUserCommand = {
    id?: string;
    name?: string | null;
    email?: string | null;
    role?: string | null;
    active?: boolean | null;
};

export type UserDto = {
    id?: string;
    name?: string | null;
    email?: string | null;
    role?: string | null;
    active?: boolean;
    createdAt?: string;
    stores?: Array<StoreDto> | null;
};

export type UserRole = 'Admin' | 'Cashier';

export type ProductDtoPaginatedListWritable = {
    data?: Array<ProductDto> | null;
    page?: number;
    limit?: number;
    total?: number;
};

export type PostApiAuthLoginData = {
    body?: LoginCommand;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRefreshTokenData = {
    body?: RefreshTokenCommand;
    path?: never;
    query?: never;
    url: '/api/Auth/refresh-token';
};

export type PostApiAuthRefreshTokenResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthRefreshTokenResponse = PostApiAuthRefreshTokenResponses[keyof PostApiAuthRefreshTokenResponses];

export type GetApiBrandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Brands';
};

export type GetApiBrandsResponses = {
    /**
     * OK
     */
    200: Array<BrandDto>;
};

export type GetApiBrandsResponse = GetApiBrandsResponses[keyof GetApiBrandsResponses];

export type PostApiBrandsData = {
    body?: {
        NameEn?: string;
        NameAr?: string;
        DescriptionEn?: string;
        DescriptionAr?: string;
        Website?: string;
        Country?: string;
        Active?: boolean;
        Image?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/Brands';
};

export type PostApiBrandsResponses = {
    /**
     * OK
     */
    200: BrandDto;
};

export type PostApiBrandsResponse = PostApiBrandsResponses[keyof PostApiBrandsResponses];

export type DeleteApiBrandsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Brands/{id}';
};

export type DeleteApiBrandsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBrandsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Brands/{id}';
};

export type GetApiBrandsByIdResponses = {
    /**
     * OK
     */
    200: BrandDto;
};

export type GetApiBrandsByIdResponse = GetApiBrandsByIdResponses[keyof GetApiBrandsByIdResponses];

export type PutApiBrandsByIdData = {
    body?: {
        NameEn?: string;
        NameAr?: string;
        DescriptionEn?: string;
        DescriptionAr?: string;
        Website?: string;
        Country?: string;
        Active?: boolean;
        Image?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Brands/{id}';
};

export type PutApiBrandsByIdResponses = {
    /**
     * OK
     */
    200: BrandDto;
};

export type PutApiBrandsByIdResponse = PutApiBrandsByIdResponses[keyof PutApiBrandsByIdResponses];

export type GetApiCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Categories';
};

export type GetApiCategoriesResponses = {
    /**
     * OK
     */
    200: Array<CategoryDto>;
};

export type GetApiCategoriesResponse = GetApiCategoriesResponses[keyof GetApiCategoriesResponses];

export type PostApiCategoriesData = {
    body?: {
        NameEn?: string;
        NameAr?: string;
        DescriptionEn?: string;
        DescriptionAr?: string;
        IconName?: string;
        Color?: string;
        ParentId?: string;
        Active?: boolean;
        Image?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/Categories';
};

export type PostApiCategoriesResponses = {
    /**
     * OK
     */
    200: CategoryDto;
};

export type PostApiCategoriesResponse = PostApiCategoriesResponses[keyof PostApiCategoriesResponses];

export type GetApiCategoriesTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Categories/tree';
};

export type GetApiCategoriesTreeResponses = {
    /**
     * OK
     */
    200: Array<CategoryDto>;
};

export type GetApiCategoriesTreeResponse = GetApiCategoriesTreeResponses[keyof GetApiCategoriesTreeResponses];

export type DeleteApiCategoriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Categories/{id}';
};

export type DeleteApiCategoriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCategoriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Categories/{id}';
};

export type GetApiCategoriesByIdResponses = {
    /**
     * OK
     */
    200: CategoryDto;
};

export type GetApiCategoriesByIdResponse = GetApiCategoriesByIdResponses[keyof GetApiCategoriesByIdResponses];

export type PutApiCategoriesByIdData = {
    body?: {
        NameEn?: string;
        NameAr?: string;
        DescriptionEn?: string;
        DescriptionAr?: string;
        IconName?: string;
        Color?: string;
        ParentId?: string;
        Active?: boolean;
        Image?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Categories/{id}';
};

export type PutApiCategoriesByIdResponses = {
    /**
     * OK
     */
    200: CategoryDto;
};

export type PutApiCategoriesByIdResponse = PutApiCategoriesByIdResponses[keyof PutApiCategoriesByIdResponses];

export type GetApiCustomersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Customers';
};

export type GetApiCustomersResponses = {
    /**
     * OK
     */
    200: Array<CustomerDto>;
};

export type GetApiCustomersResponse = GetApiCustomersResponses[keyof GetApiCustomersResponses];

export type PostApiCustomersData = {
    body?: CreateCustomerCommand;
    path?: never;
    query?: never;
    url: '/api/Customers';
};

export type PostApiCustomersResponses = {
    /**
     * OK
     */
    200: CustomerDto;
};

export type PostApiCustomersResponse = PostApiCustomersResponses[keyof PostApiCustomersResponses];

export type DeleteApiCustomersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Customers/{id}';
};

export type DeleteApiCustomersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCustomersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Customers/{id}';
};

export type GetApiCustomersByIdResponses = {
    /**
     * OK
     */
    200: CustomerDto;
};

export type GetApiCustomersByIdResponse = GetApiCustomersByIdResponses[keyof GetApiCustomersByIdResponses];

export type PutApiCustomersByIdData = {
    body?: UpdateCustomerCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Customers/{id}';
};

export type PutApiCustomersByIdResponses = {
    /**
     * OK
     */
    200: CustomerDto;
};

export type PutApiCustomersByIdResponse = PutApiCustomersByIdResponses[keyof PutApiCustomersByIdResponses];

export type GetApiCustomersByIdInvoicesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Customers/{id}/invoices';
};

export type GetApiCustomersByIdInvoicesResponses = {
    /**
     * OK
     */
    200: Array<PaymentInvoiceDto>;
};

export type GetApiCustomersByIdInvoicesResponse = GetApiCustomersByIdInvoicesResponses[keyof GetApiCustomersByIdInvoicesResponses];

export type GetApiDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Dashboard/stats';
};

export type GetApiDashboardStatsResponses = {
    /**
     * OK
     */
    200: DashboardStatsDto;
};

export type GetApiDashboardStatsResponse = GetApiDashboardStatsResponses[keyof GetApiDashboardStatsResponses];

export type GetApiDashboardRecentOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Dashboard/recent-orders';
};

export type GetApiDashboardRecentOrdersResponses = {
    /**
     * OK
     */
    200: Array<RecentOrderDto>;
};

export type GetApiDashboardRecentOrdersResponse = GetApiDashboardRecentOrdersResponses[keyof GetApiDashboardRecentOrdersResponses];

export type GetApiDashboardStockLevelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Dashboard/stock-levels';
};

export type GetApiDashboardStockLevelsResponses = {
    /**
     * OK
     */
    200: Array<StockLevelDto>;
};

export type GetApiDashboardStockLevelsResponse = GetApiDashboardStockLevelsResponses[keyof GetApiDashboardStockLevelsResponses];

export type GetApiDashboardTopProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Dashboard/top-products';
};

export type GetApiDashboardTopProductsResponses = {
    /**
     * OK
     */
    200: Array<TopProductDto>;
};

export type GetApiDashboardTopProductsResponse = GetApiDashboardTopProductsResponses[keyof GetApiDashboardTopProductsResponses];

export type GetApiDashboardHourlySalesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Dashboard/hourly-sales';
};

export type GetApiDashboardHourlySalesResponses = {
    /**
     * OK
     */
    200: Array<HourlySaleDto>;
};

export type GetApiDashboardHourlySalesResponse = GetApiDashboardHourlySalesResponses[keyof GetApiDashboardHourlySalesResponses];

export type GetApiExpenseCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ExpenseCategories';
};

export type GetApiExpenseCategoriesResponses = {
    /**
     * OK
     */
    200: Array<ExpenseCategoryDto>;
};

export type GetApiExpenseCategoriesResponse = GetApiExpenseCategoriesResponses[keyof GetApiExpenseCategoriesResponses];

export type PostApiExpenseCategoriesData = {
    body?: CreateExpenseCategoryCommand;
    path?: never;
    query?: never;
    url: '/api/ExpenseCategories';
};

export type PostApiExpenseCategoriesResponses = {
    /**
     * OK
     */
    200: ExpenseCategoryDto;
};

export type PostApiExpenseCategoriesResponse = PostApiExpenseCategoriesResponses[keyof PostApiExpenseCategoriesResponses];

export type DeleteApiExpenseCategoriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ExpenseCategories/{id}';
};

export type DeleteApiExpenseCategoriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiExpenseCategoriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ExpenseCategories/{id}';
};

export type GetApiExpenseCategoriesByIdResponses = {
    /**
     * OK
     */
    200: ExpenseCategoryDto;
};

export type GetApiExpenseCategoriesByIdResponse = GetApiExpenseCategoriesByIdResponses[keyof GetApiExpenseCategoriesByIdResponses];

export type PutApiExpenseCategoriesByIdData = {
    body?: UpdateExpenseCategoryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ExpenseCategories/{id}';
};

export type PutApiExpenseCategoriesByIdResponses = {
    /**
     * OK
     */
    200: ExpenseCategoryDto;
};

export type PutApiExpenseCategoriesByIdResponse = PutApiExpenseCategoriesByIdResponses[keyof PutApiExpenseCategoriesByIdResponses];

export type GetApiExpensesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Expenses';
};

export type GetApiExpensesResponses = {
    /**
     * OK
     */
    200: Array<ExpenseDto>;
};

export type GetApiExpensesResponse = GetApiExpensesResponses[keyof GetApiExpensesResponses];

export type PostApiExpensesData = {
    body?: CreateExpenseRequest;
    path?: never;
    query?: never;
    url: '/api/Expenses';
};

export type PostApiExpensesResponses = {
    /**
     * OK
     */
    200: ExpenseDto;
};

export type PostApiExpensesResponse = PostApiExpensesResponses[keyof PostApiExpensesResponses];

export type DeleteApiExpensesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Expenses/{id}';
};

export type DeleteApiExpensesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiExpensesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Expenses/{id}';
};

export type GetApiExpensesByIdResponses = {
    /**
     * OK
     */
    200: ExpenseDto;
};

export type GetApiExpensesByIdResponse = GetApiExpensesByIdResponses[keyof GetApiExpensesByIdResponses];

export type PutApiExpensesByIdData = {
    body?: UpdateExpenseCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Expenses/{id}';
};

export type PutApiExpensesByIdResponses = {
    /**
     * OK
     */
    200: ExpenseDto;
};

export type PutApiExpensesByIdResponse = PutApiExpensesByIdResponses[keyof PutApiExpensesByIdResponses];

export type GetApiInventoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Inventory';
};

export type GetApiInventoryResponses = {
    /**
     * OK
     */
    200: Array<InventoryItemDto>;
};

export type GetApiInventoryResponse = GetApiInventoryResponses[keyof GetApiInventoryResponses];

export type GetApiInventoryLowStockData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Inventory/low-stock';
};

export type GetApiInventoryLowStockResponses = {
    /**
     * OK
     */
    200: Array<InventoryItemDto>;
};

export type GetApiInventoryLowStockResponse = GetApiInventoryLowStockResponses[keyof GetApiInventoryLowStockResponses];

export type PostApiInventoryByProductIdAddStockData = {
    body?: AddStockRequest;
    path: {
        productId: string;
    };
    query?: never;
    url: '/api/Inventory/{productId}/add-stock';
};

export type PostApiInventoryByProductIdAddStockResponses = {
    /**
     * OK
     */
    200: InventoryItemDto;
};

export type PostApiInventoryByProductIdAddStockResponse = PostApiInventoryByProductIdAddStockResponses[keyof PostApiInventoryByProductIdAddStockResponses];

export type GetApiMyStoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/MyStores';
};

export type GetApiMyStoresResponses = {
    /**
     * OK
     */
    200: Array<StoreDto>;
};

export type GetApiMyStoresResponse = GetApiMyStoresResponses[keyof GetApiMyStoresResponses];

export type GetApiOrdersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Orders';
};

export type GetApiOrdersResponses = {
    /**
     * OK
     */
    200: Array<OrderDto>;
};

export type GetApiOrdersResponse = GetApiOrdersResponses[keyof GetApiOrdersResponses];

export type PostApiOrdersData = {
    body?: CreateOrderRequest;
    path?: never;
    query?: never;
    url: '/api/Orders';
};

export type PostApiOrdersResponses = {
    /**
     * OK
     */
    200: OrderDto;
};

export type PostApiOrdersResponse = PostApiOrdersResponses[keyof PostApiOrdersResponses];

export type GetApiOrdersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Orders/{id}';
};

export type GetApiOrdersByIdResponses = {
    /**
     * OK
     */
    200: OrderDto;
};

export type GetApiOrdersByIdResponse = GetApiOrdersByIdResponses[keyof GetApiOrdersByIdResponses];

export type GetApiPaymentInvoicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/PaymentInvoices';
};

export type GetApiPaymentInvoicesResponses = {
    /**
     * OK
     */
    200: Array<PaymentInvoiceDto>;
};

export type GetApiPaymentInvoicesResponse = GetApiPaymentInvoicesResponses[keyof GetApiPaymentInvoicesResponses];

export type PostApiPaymentInvoicesData = {
    body?: CreatePaymentInvoiceRequest;
    path?: never;
    query?: never;
    url: '/api/PaymentInvoices';
};

export type PostApiPaymentInvoicesResponses = {
    /**
     * OK
     */
    200: PaymentInvoiceDto;
};

export type PostApiPaymentInvoicesResponse = PostApiPaymentInvoicesResponses[keyof PostApiPaymentInvoicesResponses];

export type GetApiPaymentInvoicesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/PaymentInvoices/{id}';
};

export type GetApiPaymentInvoicesByIdResponses = {
    /**
     * OK
     */
    200: PaymentInvoiceDto;
};

export type GetApiPaymentInvoicesByIdResponse = GetApiPaymentInvoicesByIdResponses[keyof GetApiPaymentInvoicesByIdResponses];

export type GetApiPaymentInvoicesOverdueData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/PaymentInvoices/overdue';
};

export type GetApiPaymentInvoicesOverdueResponses = {
    /**
     * OK
     */
    200: Array<PaymentInvoiceDto>;
};

export type GetApiPaymentInvoicesOverdueResponse = GetApiPaymentInvoicesOverdueResponses[keyof GetApiPaymentInvoicesOverdueResponses];

export type PostApiPaymentInvoicesByIdPayData = {
    body?: MarkInvoicePaidRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/PaymentInvoices/{id}/pay';
};

export type PostApiPaymentInvoicesByIdPayResponses = {
    /**
     * OK
     */
    200: PaymentInvoiceDto;
};

export type PostApiPaymentInvoicesByIdPayResponse = PostApiPaymentInvoicesByIdPayResponses[keyof PostApiPaymentInvoicesByIdPayResponses];

export type GetApiProductsData = {
    body?: never;
    path?: never;
    query?: {
        Page?: number;
        Limit?: number;
        Search?: string;
        CategoryId?: string;
        BrandId?: string;
        ActiveOnly?: boolean;
        SortBy?: string;
        SortDesc?: boolean;
    };
    url: '/api/Products';
};

export type GetApiProductsResponses = {
    /**
     * OK
     */
    200: ProductDtoPaginatedList;
};

export type GetApiProductsResponse = GetApiProductsResponses[keyof GetApiProductsResponses];

export type PostApiProductsData = {
    body?: {
        NameEn?: string;
        NameAr?: string;
        DescriptionEn?: string;
        DescriptionAr?: string;
        Sku?: string;
        Barcode?: string;
        CategoryId?: string;
        BrandId?: string;
        CostPrice?: number;
        SellPrice?: number;
        StockQty?: number;
        ReorderLevel?: number;
        BaseUnitId?: string;
        PurchaseUnitId?: string;
        ConversionFactor?: number;
        TaxId?: string;
        Active?: boolean;
        Images?: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/api/Products';
};

export type PostApiProductsResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type PostApiProductsResponse = PostApiProductsResponses[keyof PostApiProductsResponses];

export type DeleteApiProductsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Products/{id}';
};

export type DeleteApiProductsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiProductsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Products/{id}';
};

export type GetApiProductsByIdResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type GetApiProductsByIdResponse = GetApiProductsByIdResponses[keyof GetApiProductsByIdResponses];

export type PutApiProductsByIdData = {
    body?: {
        NameEn?: string;
        NameAr?: string;
        DescriptionEn?: string;
        DescriptionAr?: string;
        Sku?: string;
        Barcode?: string;
        CategoryId?: string;
        BrandId?: string;
        CostPrice?: number;
        SellPrice?: number;
        StockQty?: number;
        ReorderLevel?: number;
        BaseUnitId?: string;
        PurchaseUnitId?: string;
        ConversionFactor?: number;
        TaxId?: string;
        Active?: boolean;
        Images?: Array<Blob | File>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Products/{id}';
};

export type PutApiProductsByIdResponses = {
    /**
     * OK
     */
    200: ProductDto;
};

export type PutApiProductsByIdResponse = PutApiProductsByIdResponses[keyof PutApiProductsByIdResponses];

export type PostApiProductsByIdImagesData = {
    body?: {
        files?: Array<Blob | File>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Products/{id}/images';
};

export type PostApiProductsByIdImagesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiProductsByProductIdImagesByImageIdData = {
    body?: never;
    path: {
        productId: string;
        imageId: string;
    };
    query?: never;
    url: '/api/Products/{productId}/images/{imageId}';
};

export type DeleteApiProductsByProductIdImagesByImageIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiProductsByProductIdImagesReorderData = {
    body?: Array<ImageOrder>;
    path: {
        productId: string;
    };
    query?: never;
    url: '/api/Products/{productId}/images/reorder';
};

export type PutApiProductsByProductIdImagesReorderResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPurchaseInvoicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/PurchaseInvoices';
};

export type GetApiPurchaseInvoicesResponses = {
    /**
     * OK
     */
    200: Array<PurchaseInvoiceDto>;
};

export type GetApiPurchaseInvoicesResponse = GetApiPurchaseInvoicesResponses[keyof GetApiPurchaseInvoicesResponses];

export type PostApiPurchaseInvoicesData = {
    body?: CreatePurchaseInvoiceRequest;
    path?: never;
    query?: never;
    url: '/api/PurchaseInvoices';
};

export type PostApiPurchaseInvoicesResponses = {
    /**
     * OK
     */
    200: PurchaseInvoiceDto;
};

export type PostApiPurchaseInvoicesResponse = PostApiPurchaseInvoicesResponses[keyof PostApiPurchaseInvoicesResponses];

export type GetApiPurchaseInvoicesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/PurchaseInvoices/{id}';
};

export type GetApiPurchaseInvoicesByIdResponses = {
    /**
     * OK
     */
    200: PurchaseInvoiceDto;
};

export type GetApiPurchaseInvoicesByIdResponse = GetApiPurchaseInvoicesByIdResponses[keyof GetApiPurchaseInvoicesByIdResponses];

export type GetApiPurchaseInvoicesPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/PurchaseInvoices/pending';
};

export type GetApiPurchaseInvoicesPendingResponses = {
    /**
     * OK
     */
    200: Array<PurchaseInvoiceDto>;
};

export type GetApiPurchaseInvoicesPendingResponse = GetApiPurchaseInvoicesPendingResponses[keyof GetApiPurchaseInvoicesPendingResponses];

export type PostApiPurchaseInvoicesByIdApproveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/PurchaseInvoices/{id}/approve';
};

export type PostApiPurchaseInvoicesByIdApproveResponses = {
    /**
     * OK
     */
    200: PurchaseInvoiceDto;
};

export type PostApiPurchaseInvoicesByIdApproveResponse = PostApiPurchaseInvoicesByIdApproveResponses[keyof PostApiPurchaseInvoicesByIdApproveResponses];

export type GetApiReceiptsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Receipts/{id}';
};

export type GetApiReceiptsByIdResponses = {
    /**
     * OK
     */
    200: ReceiptDto;
};

export type GetApiReceiptsByIdResponse = GetApiReceiptsByIdResponses[keyof GetApiReceiptsByIdResponses];

export type GetApiReceiptsOrderByOrderIdData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/Receipts/order/{orderId}';
};

export type GetApiReceiptsOrderByOrderIdResponses = {
    /**
     * OK
     */
    200: ReceiptDto;
};

export type GetApiReceiptsOrderByOrderIdResponse = GetApiReceiptsOrderByOrderIdResponses[keyof GetApiReceiptsOrderByOrderIdResponses];

export type GetApiReportsSummaryData = {
    body?: never;
    path?: never;
    query?: {
        StartDate?: string;
        EndDate?: string;
    };
    url: '/api/Reports/summary';
};

export type GetApiReportsSummaryResponses = {
    /**
     * OK
     */
    200: ReportSummaryDto;
};

export type GetApiReportsSummaryResponse = GetApiReportsSummaryResponses[keyof GetApiReportsSummaryResponses];

export type GetApiReportsDailySalesData = {
    body?: never;
    path?: never;
    query?: {
        StartDate?: string;
        EndDate?: string;
    };
    url: '/api/Reports/daily-sales';
};

export type GetApiReportsDailySalesResponses = {
    /**
     * OK
     */
    200: Array<DailyReportRowDto>;
};

export type GetApiReportsDailySalesResponse = GetApiReportsDailySalesResponses[keyof GetApiReportsDailySalesResponses];

export type GetApiReportsCategorySalesData = {
    body?: never;
    path?: never;
    query?: {
        StartDate?: string;
        EndDate?: string;
    };
    url: '/api/Reports/category-sales';
};

export type GetApiReportsCategorySalesResponses = {
    /**
     * OK
     */
    200: Array<CategoryReportDto>;
};

export type GetApiReportsCategorySalesResponse = GetApiReportsCategorySalesResponses[keyof GetApiReportsCategorySalesResponses];

export type GetApiReportsBrandSalesData = {
    body?: never;
    path?: never;
    query?: {
        StartDate?: string;
        EndDate?: string;
    };
    url: '/api/Reports/brand-sales';
};

export type GetApiReportsBrandSalesResponses = {
    /**
     * OK
     */
    200: Array<BrandReportDto>;
};

export type GetApiReportsBrandSalesResponse = GetApiReportsBrandSalesResponses[keyof GetApiReportsBrandSalesResponses];

export type GetApiStoresData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Stores';
};

export type GetApiStoresResponses = {
    /**
     * OK
     */
    200: Array<StoreDto>;
};

export type GetApiStoresResponse = GetApiStoresResponses[keyof GetApiStoresResponses];

export type PostApiStoresData = {
    body?: CreateStoreCommand;
    path?: never;
    query?: never;
    url: '/api/Stores';
};

export type PostApiStoresResponses = {
    /**
     * OK
     */
    200: StoreDto;
};

export type PostApiStoresResponse = PostApiStoresResponses[keyof PostApiStoresResponses];

export type DeleteApiStoresByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Stores/{id}';
};

export type DeleteApiStoresByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiStoresByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Stores/{id}';
};

export type GetApiStoresByIdResponses = {
    /**
     * OK
     */
    200: StoreDto;
};

export type GetApiStoresByIdResponse = GetApiStoresByIdResponses[keyof GetApiStoresByIdResponses];

export type PutApiStoresByIdData = {
    body?: UpdateStoreCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Stores/{id}';
};

export type PutApiStoresByIdResponses = {
    /**
     * OK
     */
    200: StoreDto;
};

export type PutApiStoresByIdResponse = PutApiStoresByIdResponses[keyof PutApiStoresByIdResponses];

export type DeleteApiStoresByStoreIdUsersByUserIdData = {
    body?: never;
    path: {
        storeId: string;
        userId: string;
    };
    query?: never;
    url: '/api/Stores/{storeId}/users/{userId}';
};

export type DeleteApiStoresByStoreIdUsersByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiStoresByStoreIdUsersByUserIdData = {
    body?: AssignUserToStoreCommand;
    path: {
        storeId: string;
        userId: string;
    };
    query?: never;
    url: '/api/Stores/{storeId}/users/{userId}';
};

export type PostApiStoresByStoreIdUsersByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSuppliersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Suppliers';
};

export type GetApiSuppliersResponses = {
    /**
     * OK
     */
    200: Array<SupplierDto>;
};

export type GetApiSuppliersResponse = GetApiSuppliersResponses[keyof GetApiSuppliersResponses];

export type PostApiSuppliersData = {
    body?: CreateSupplierCommand;
    path?: never;
    query?: never;
    url: '/api/Suppliers';
};

export type PostApiSuppliersResponses = {
    /**
     * OK
     */
    200: SupplierDto;
};

export type PostApiSuppliersResponse = PostApiSuppliersResponses[keyof PostApiSuppliersResponses];

export type DeleteApiSuppliersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Suppliers/{id}';
};

export type DeleteApiSuppliersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSuppliersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Suppliers/{id}';
};

export type GetApiSuppliersByIdResponses = {
    /**
     * OK
     */
    200: SupplierDto;
};

export type GetApiSuppliersByIdResponse = GetApiSuppliersByIdResponses[keyof GetApiSuppliersByIdResponses];

export type PutApiSuppliersByIdData = {
    body?: UpdateSupplierCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Suppliers/{id}';
};

export type PutApiSuppliersByIdResponses = {
    /**
     * OK
     */
    200: SupplierDto;
};

export type PutApiSuppliersByIdResponse = PutApiSuppliersByIdResponses[keyof PutApiSuppliersByIdResponses];

export type GetApiSuppliersByIdPurchasesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Suppliers/{id}/purchases';
};

export type GetApiSuppliersByIdPurchasesResponses = {
    /**
     * OK
     */
    200: Array<PurchaseInvoiceDto>;
};

export type GetApiSuppliersByIdPurchasesResponse = GetApiSuppliersByIdPurchasesResponses[keyof GetApiSuppliersByIdPurchasesResponses];

export type GetApiTaxesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Taxes';
};

export type GetApiTaxesResponses = {
    /**
     * OK
     */
    200: Array<TaxDto>;
};

export type GetApiTaxesResponse = GetApiTaxesResponses[keyof GetApiTaxesResponses];

export type PostApiTaxesData = {
    body?: CreateTaxCommand;
    path?: never;
    query?: never;
    url: '/api/Taxes';
};

export type PostApiTaxesResponses = {
    /**
     * OK
     */
    200: TaxDto;
};

export type PostApiTaxesResponse = PostApiTaxesResponses[keyof PostApiTaxesResponses];

export type DeleteApiTaxesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Taxes/{id}';
};

export type DeleteApiTaxesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTaxesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Taxes/{id}';
};

export type GetApiTaxesByIdResponses = {
    /**
     * OK
     */
    200: TaxDto;
};

export type GetApiTaxesByIdResponse = GetApiTaxesByIdResponses[keyof GetApiTaxesByIdResponses];

export type PutApiTaxesByIdData = {
    body?: UpdateTaxCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Taxes/{id}';
};

export type PutApiTaxesByIdResponses = {
    /**
     * OK
     */
    200: TaxDto;
};

export type PutApiTaxesByIdResponse = PutApiTaxesByIdResponses[keyof PutApiTaxesByIdResponses];

export type PostApiTaxesByIdSetDefaultData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Taxes/{id}/set-default';
};

export type PostApiTaxesByIdSetDefaultResponses = {
    /**
     * OK
     */
    200: TaxDto;
};

export type PostApiTaxesByIdSetDefaultResponse = PostApiTaxesByIdSetDefaultResponses[keyof PostApiTaxesByIdSetDefaultResponses];

export type GetApiUnitConversionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/UnitConversions';
};

export type GetApiUnitConversionsResponses = {
    /**
     * OK
     */
    200: Array<UnitConversionDto>;
};

export type GetApiUnitConversionsResponse = GetApiUnitConversionsResponses[keyof GetApiUnitConversionsResponses];

export type PostApiUnitConversionsData = {
    body?: CreateUnitConversionCommand;
    path?: never;
    query?: never;
    url: '/api/UnitConversions';
};

export type PostApiUnitConversionsResponses = {
    /**
     * OK
     */
    200: UnitConversionDto;
};

export type PostApiUnitConversionsResponse = PostApiUnitConversionsResponses[keyof PostApiUnitConversionsResponses];

export type DeleteApiUnitConversionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/UnitConversions/{id}';
};

export type DeleteApiUnitConversionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUnitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Units';
};

export type GetApiUnitsResponses = {
    /**
     * OK
     */
    200: Array<UnitDto>;
};

export type GetApiUnitsResponse = GetApiUnitsResponses[keyof GetApiUnitsResponses];

export type PostApiUnitsData = {
    body?: CreateUnitCommand;
    path?: never;
    query?: never;
    url: '/api/Units';
};

export type PostApiUnitsResponses = {
    /**
     * OK
     */
    200: UnitDto;
};

export type PostApiUnitsResponse = PostApiUnitsResponses[keyof PostApiUnitsResponses];

export type DeleteApiUnitsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Units/{id}';
};

export type DeleteApiUnitsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUnitsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Units/{id}';
};

export type GetApiUnitsByIdResponses = {
    /**
     * OK
     */
    200: UnitDto;
};

export type GetApiUnitsByIdResponse = GetApiUnitsByIdResponses[keyof GetApiUnitsByIdResponses];

export type PutApiUnitsByIdData = {
    body?: UpdateUnitCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Units/{id}';
};

export type PutApiUnitsByIdResponses = {
    /**
     * OK
     */
    200: UnitDto;
};

export type PutApiUnitsByIdResponse = PutApiUnitsByIdResponses[keyof PutApiUnitsByIdResponses];

export type GetApiUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users';
};

export type GetApiUsersResponses = {
    /**
     * OK
     */
    200: Array<UserDto>;
};

export type GetApiUsersResponse = GetApiUsersResponses[keyof GetApiUsersResponses];

export type PostApiUsersData = {
    body?: CreateUserCommand;
    path?: never;
    query?: never;
    url: '/api/Users';
};

export type PostApiUsersResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];

export type DeleteApiUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type DeleteApiUsersByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type GetApiUsersByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetApiUsersByIdResponse = GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PutApiUsersByIdData = {
    body?: UpdateUserCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/Users/{id}';
};

export type PutApiUsersByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PutApiUsersByIdResponse = PutApiUsersByIdResponses[keyof PutApiUsersByIdResponses];

export type PostApiUsersChangePasswordData = {
    body?: ChangePasswordCommand;
    path?: never;
    query?: never;
    url: '/api/Users/change-password';
};

export type PostApiUsersChangePasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};
